apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: flight-service
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: flight-service
    spec:
      containers:
      - name: flight-service
        image: iosr/flight-service
        ports:
        - containerPort: 8080
